# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 The Contributors to Eclipse OpenSOVD (see CONTRIBUTORS)
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0

version = 1

[[annotations]]
path = [
  "LICENSE",
  "NOTICE",
  "CONTRIBUTORS",
  "**.md",
  ".gitignore",
  "REUSE.toml",
  ".reuse/templates/**.jinja2",
  "LICENSES/**.txt",
]
SPDX-FileCopyrightText = "The Contributors to Eclipse OpenSOVD (see CONTRIBUTORS)"
SPDX-License-Identifier = "Apache-2.0"
